// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * QC Write API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package write




type SendTransactionRequest struct {

	TxnData string `json:"txnData,omitempty"`
}

// AssertSendTransactionRequestRequired checks if the required fields are not zero-ed
func AssertSendTransactionRequestRequired(obj SendTransactionRequest) error {
	return nil
}

// AssertSendTransactionRequestConstraints checks if the values respects the defined constraints
func AssertSendTransactionRequestConstraints(obj SendTransactionRequest) error {
	return nil
}
