// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * QC Write API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcwriteapi




type ErrorResponseModel struct {

	Message *string `json:"message,omitempty"`

	Status int32 `json:"status,omitempty"`
}

// AssertErrorResponseModelRequired checks if the required fields are not zero-ed
func AssertErrorResponseModelRequired(obj ErrorResponseModel) error {
	return nil
}

// AssertErrorResponseModelConstraints checks if the values respects the defined constraints
func AssertErrorResponseModelConstraints(obj ErrorResponseModel) error {
	return nil
}
