// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * QC Write API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package write

import (
	"encoding/json"
	"io"
	"net/http"
	"strings"
	"errors"
)

// WriteApiAPIController binds http requests to an api service and writes the service results to the http response
type WriteApiAPIController struct {
	service WriteApiAPIServicer
	errorHandler ErrorHandler
}

// WriteApiAPIOption for how the controller is set up.
type WriteApiAPIOption func(*WriteApiAPIController)

// WithWriteApiAPIErrorHandler inject ErrorHandler into controller
func WithWriteApiAPIErrorHandler(h ErrorHandler) WriteApiAPIOption {
	return func(c *WriteApiAPIController) {
		c.errorHandler = h
	}
}

// NewWriteApiAPIController creates a default api controller
func NewWriteApiAPIController(s WriteApiAPIServicer, opts ...WriteApiAPIOption) *WriteApiAPIController {
	controller := &WriteApiAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the WriteApiAPIController
func (c *WriteApiAPIController) Routes() Routes {
	return Routes{
		"SendTransaction": Route{
			strings.ToUpper("Post"),
			"/transactions",
			c.SendTransaction,
		},
	}
}

// SendTransaction - Send Transaction
func (c *WriteApiAPIController) SendTransaction(w http.ResponseWriter, r *http.Request) {
	sendTransactionRequestParam := SendTransactionRequest{}
	d := json.NewDecoder(r.Body)
	d.DisallowUnknownFields()
	if err := d.Decode(&sendTransactionRequestParam); err != nil && !errors.Is(err, io.EOF) {
		c.errorHandler(w, r, &ParsingError{Err: err}, nil)
		return
	}
	if err := AssertSendTransactionRequestRequired(sendTransactionRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	if err := AssertSendTransactionRequestConstraints(sendTransactionRequestParam); err != nil {
		c.errorHandler(w, r, err, nil)
		return
	}
	result, err := c.service.SendTransaction(r.Context(), sendTransactionRequestParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
