// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * QC Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi

import (
	"context"
	"net/http"
)



// ReadApiAPIRouter defines the required methods for binding the api requests to a responses for the ReadApiAPI
// The ReadApiAPIRouter implementation should parse necessary information from the http request,
// pass the data to a ReadApiAPIServicer to perform the required actions, then write the service results to the http response.
type ReadApiAPIRouter interface { 
	GetAccountDetails(http.ResponseWriter, *http.Request)
	GetTransaction(http.ResponseWriter, *http.Request)
}


// ReadApiAPIServicer defines the api actions for the ReadApiAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ReadApiAPIServicer interface { 
	GetAccountDetails(context.Context, string) (ImplResponse, error)
	GetTransaction(context.Context, string) (ImplResponse, error)
}
