// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * QC Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package read




type TransactionDetails struct {

	// The hash of the block in which the transaction was executed. If this transaction is pending or was discarded, this will be null.
	BlockHash *string `json:"blockHash,omitempty"`

	// The number of the block in which the transaction was executed. If this transaction is pending or was discarded, this will be null.
	BlockNumber *int64 `json:"blockNumber,omitempty"`

	From string `json:"from,omitempty"`

	Gas string `json:"gas,omitempty"`

	GasPrice string `json:"gasPrice,omitempty"`

	Hash string `json:"hash,omitempty"`

	Input string `json:"input,omitempty"`

	Nonce int64 `json:"nonce,omitempty"`

	To *string `json:"to,omitempty"`

	Value string `json:"value,omitempty"`

	Receipt TransactionReceipt `json:"receipt,omitempty"`
}

// AssertTransactionDetailsRequired checks if the required fields are not zero-ed
func AssertTransactionDetailsRequired(obj TransactionDetails) error {
	if err := AssertTransactionReceiptRequired(obj.Receipt); err != nil {
		return err
	}
	return nil
}

// AssertTransactionDetailsConstraints checks if the values respects the defined constraints
func AssertTransactionDetailsConstraints(obj TransactionDetails) error {
	if err := AssertTransactionReceiptConstraints(obj.Receipt); err != nil {
		return err
	}
	return nil
}
