// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * QC Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi




type TransactionReceipt struct {

	CumulativeGasUsed string `json:"cumulativeGasUsed,omitempty"`

	EffectiveGasPrice string `json:"effectiveGasPrice,omitempty"`

	GasUsed string `json:"gasUsed,omitempty"`

	Status string `json:"status,omitempty"`

	Hash string `json:"hash,omitempty"`

	Type string `json:"type,omitempty"`
}

// AssertTransactionReceiptRequired checks if the required fields are not zero-ed
func AssertTransactionReceiptRequired(obj TransactionReceipt) error {
	return nil
}

// AssertTransactionReceiptConstraints checks if the values respects the defined constraints
func AssertTransactionReceiptConstraints(obj TransactionReceipt) error {
	return nil
}
