// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * QC Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi




type AccountDetailsResponse struct {

	Result AccountDetails `json:"result,omitempty"`
}

// AssertAccountDetailsResponseRequired checks if the required fields are not zero-ed
func AssertAccountDetailsResponseRequired(obj AccountDetailsResponse) error {
	if err := AssertAccountDetailsRequired(obj.Result); err != nil {
		return err
	}
	return nil
}

// AssertAccountDetailsResponseConstraints checks if the values respects the defined constraints
func AssertAccountDetailsResponseConstraints(obj AccountDetailsResponse) error {
	if err := AssertAccountDetailsConstraints(obj.Result); err != nil {
		return err
	}
	return nil
}
