// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * QC Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package qcreadapi




type TransactionResponse struct {

	Result TransactionDetails `json:"result,omitempty"`
}

// AssertTransactionResponseRequired checks if the required fields are not zero-ed
func AssertTransactionResponseRequired(obj TransactionResponse) error {
	if err := AssertTransactionDetailsRequired(obj.Result); err != nil {
		return err
	}
	return nil
}

// AssertTransactionResponseConstraints checks if the values respects the defined constraints
func AssertTransactionResponseConstraints(obj TransactionResponse) error {
	if err := AssertTransactionDetailsConstraints(obj.Result); err != nil {
		return err
	}
	return nil
}
