// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * QC Read API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 */

package read




type AccountDetails struct {

	Balance *string `json:"balance,omitempty"`

	Nonce *int64 `json:"nonce,omitempty"`

	// The block number as of which the details were retrieved
	BlockNumber *int64 `json:"blockNumber,omitempty"`
}

// AssertAccountDetailsRequired checks if the required fields are not zero-ed
func AssertAccountDetailsRequired(obj AccountDetails) error {
	return nil
}

// AssertAccountDetailsConstraints checks if the values respects the defined constraints
func AssertAccountDetailsConstraints(obj AccountDetails) error {
	return nil
}
